// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {workshop} from '../models';

export function AppendHistoryRow(arg1:domain.ServerRow):Promise<void>;

export function ApplyServerFilters(arg1:Array<domain.ServerRow>,arg2:domain.FilterState):Promise<Array<domain.ServerRow>>;

export function ClearQuickFavorite():Promise<void>;

export function DeleteWorkshopItems(arg1:Array<string>):Promise<void>;

export function DiscoverMapNames(arg1:Array<domain.ServerRow>):Promise<Array<string>>;

export function EnrichServerMods(arg1:string,arg2:number):Promise<Array<string>>;

export function FetchSteamServers():Promise<Array<domain.ServerRow>>;

export function LaunchConnect(arg1:domain.ServerRow):Promise<void>;

export function ListWorkshopItems():Promise<Array<workshop.Item>>;

export function LoadSettings():Promise<domain.Settings>;

export function MergeFavoriteSnapshots(arg1:Array<domain.ServerRow>):Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function RefreshServersPing(arg1:Array<domain.ServerRow>):Promise<Array<domain.ServerRow>>;

export function RemoveFavorite(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RemoveHistoryIndex(arg1:number):Promise<void>;

export function ResolveBattlemetricsID(arg1:string):Promise<domain.ServerRow>;

export function SaveSettings(arg1:domain.Settings):Promise<void>;

export function ScanLAN():Promise<Array<domain.ServerRow>>;

export function SetQuickFavorite(arg1:domain.ServerRow,arg2:string):Promise<void>;

export function ToggleFavoriteRow(arg1:domain.ServerRow):Promise<void>;

export function ValidateSteamAPIKey(arg1:string):Promise<domain.SteamKeyValidation>;

export function WorkshopPage(arg1:string):Promise<void>;
