// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendHistoryRow(arg1) {
  return window['go']['main']['App']['AppendHistoryRow'](arg1);
}

export function ApplyServerFilters(arg1, arg2) {
  return window['go']['main']['App']['ApplyServerFilters'](arg1, arg2);
}

export function ClearQuickFavorite() {
  return window['go']['main']['App']['ClearQuickFavorite']();
}

export function DeleteWorkshopItems(arg1) {
  return window['go']['main']['App']['DeleteWorkshopItems'](arg1);
}

export function DiscoverMapNames(arg1) {
  return window['go']['main']['App']['DiscoverMapNames'](arg1);
}

export function EnrichServerMods(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnrichServerMods'](arg1, arg2, arg3);
}

export function FetchSteamServers() {
  return window['go']['main']['App']['FetchSteamServers']();
}

export function LaunchConnect(arg1) {
  return window['go']['main']['App']['LaunchConnect'](arg1);
}

export function ListWorkshopItems() {
  return window['go']['main']['App']['ListWorkshopItems']();
}

export function LoadBrowseSession() {
  return window['go']['main']['App']['LoadBrowseSession']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function MergeFavoriteSnapshots(arg1) {
  return window['go']['main']['App']['MergeFavoriteSnapshots'](arg1);
}

export function MergeKnownMapNamesFromRows(arg1) {
  return window['go']['main']['App']['MergeKnownMapNamesFromRows'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function RefreshServersPing(arg1) {
  return window['go']['main']['App']['RefreshServersPing'](arg1);
}

export function RemoveFavorite(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveFavorite'](arg1, arg2, arg3);
}

export function RemoveHistoryIndex(arg1) {
  return window['go']['main']['App']['RemoveHistoryIndex'](arg1);
}

export function ResolveBattlemetricsID(arg1) {
  return window['go']['main']['App']['ResolveBattlemetricsID'](arg1);
}

export function SaveBrowseSession(arg1) {
  return window['go']['main']['App']['SaveBrowseSession'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanLAN() {
  return window['go']['main']['App']['ScanLAN']();
}

export function SetQuickFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetQuickFavorite'](arg1, arg2);
}

export function ToggleFavoriteRow(arg1) {
  return window['go']['main']['App']['ToggleFavoriteRow'](arg1);
}

export function ValidateSteamAPIKey(arg1) {
  return window['go']['main']['App']['ValidateSteamAPIKey'](arg1);
}

export function WorkshopPage(arg1) {
  return window['go']['main']['App']['WorkshopPage'](arg1);
}
